/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_ButtonManager */

#ifndef _Included_app_ButtonManager
#define _Included_app_ButtonManager
#ifdef __cplusplus
extern "C" {
#endif
#undef app_ButtonManager_MIN_PRIORITY
#define app_ButtonManager_MIN_PRIORITY 1L
#undef app_ButtonManager_NORM_PRIORITY
#define app_ButtonManager_NORM_PRIORITY 5L
#undef app_ButtonManager_MAX_PRIORITY
#define app_ButtonManager_MAX_PRIORITY 10L
/*
 * Class:     app_ButtonManager
 * Method:    getButtonStates
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_ButtonManager_getButtonStates
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
